### PR TITLE
mode specs are signs of old lisp projects; slime can detect them.

### PR DESCRIPTION
**Pull request by guicho271828**
Also, emacs shows warnings when opening those files

### CODE REVIEW

**Comment by rpgoldman** [comment]
Thanks, this looks good.  I will merge it.

**Comment by lispm** [comment]
Not everyone is using SLIME.

**Comment by rpgoldman** [comment]
@lispm So are these mode specs useful in the Lispworks IDE?  (I am guessing that on the basis of your suggestion that I fix the GC).

**Comment by guicho271828** [comment]
I'd say "at least" slime... Im pretty sure slimv and atom-slime would launch the proper language mode  just from the file extensions, and also detect the package. Those file local variables are redundant and emacs-specific. (I don't say GNU Emacs, rather the broader Emacs editors like hemlock)

**Comment by lispm** [comment]
Most editors will assume Common Lisp mode and will search for an IN-PACKAGE in the file.

The more useful part is when the encoding is specified in the attributes, then the editor might be able open the file in the right encoding. I use that for UTF-8 files for example.

**Comment by rpgoldman** [comment]
If the mode lines cause problems for anyone, I believe it's possible to configure how they will be handled by the editor through [directory locals](https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Local-Variables.html), and then the users can configure the variables for themselves.

**Pull request merged**
